#!/bin/sh
# Seeds Vault dev-mode with the KV mount, policy and AppRole the demo apps
# expect. Writes role_id / secret_id to /out/.env so the demo apps running
# on the host can pick them up.
set -eu

VAULT_ADDR="${VAULT_ADDR:-http://vault:8200}"
export VAULT_ADDR
export VAULT_TOKEN="${VAULT_TOKEN:-myroot}"

echo ">>> Waiting for Vault to be ready..."
for i in $(seq 1 30); do
  if vault status >/dev/null 2>&1; then break; fi
  sleep 1
done

echo ">>> Enabling KV v2 secrets engine at cftsearch/"
vault secrets disable cftsearch >/dev/null 2>&1 || true
vault secrets enable -path=cftsearch kv-v2

echo ">>> Enabling AppRole auth method"
vault auth disable approle >/dev/null 2>&1 || true
vault auth enable approle

echo ">>> Writing policy otto-config-policy"
cat <<'EOF' | vault policy write otto-config-policy -
path "cftsearch/data/*" {
  capabilities = ["create", "read", "update", "delete", "list"]
}
path "cftsearch/metadata/*" {
  capabilities = ["list", "read"]
}
EOF

echo ">>> Creating AppRole otto-config"
vault write auth/approle/role/otto-config \
    policies="otto-config-policy" \
    token_ttl=6m \
    token_max_ttl=10m >/dev/null

ROLE_ID=$(vault read -field=role_id auth/approle/role/otto-config/role-id)
SECRET_ID=$(vault write -field=secret_id -f auth/approle/role/otto-config/secret-id)

echo ">>> Seeding secret cftsearch/service/otto-config/develop/auth"
vault kv put cftsearch/service/otto-config/develop/auth \
  auth_client_id=admin \
  auth_client_secret=secret >/dev/null

echo ">>> Writing /out/.env"
cat > /out/.env <<EOF
# Generated by demo/local/init-vault.sh — source this before running the demo apps.
export VAULT_ROLE_ID=${ROLE_ID}
export VAULT_SECRET_ID=${SECRET_ID}
export AWS_ACCESS_KEY_ID=test
export AWS_SECRET_ACCESS_KEY=test
export AWS_REGION=eu-central-1
export AWS_DEFAULT_REGION=eu-central-1
export AWS_ENDPOINT_URL=http://localhost:5000
# Route only the AppConfigData data-plane calls to the local stub (moto
# does not implement 'appconfigdata'). The service-specific override
# takes precedence over AWS_ENDPOINT_URL for that one client.
export AWS_ENDPOINT_URL_APPCONFIGDATA=http://localhost:5001
EOF

echo ">>> vault bootstrap done. role_id=${ROLE_ID}"
